// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Protocol.proto

package com.chuhui.marshal.framework.transfer.google;

public interface ConsumerRequestPackageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.chuhui.marshal.framework.transfer.google.ConsumerRequestPackage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
