// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Protocol.proto

package com.chuhui.marshal.framework.transfer.google;

public interface ConsumerRequestPackageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.chuhui.marshal.framework.transfer.google.ConsumerRequestPackage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string requireProducer = 1;</code>
   */
  java.util.List<java.lang.String>
      getRequireProducerList();
  /**
   * <code>repeated string requireProducer = 1;</code>
   */
  int getRequireProducerCount();
  /**
   * <code>repeated string requireProducer = 1;</code>
   */
  java.lang.String getRequireProducer(int index);
  /**
   * <code>repeated string requireProducer = 1;</code>
   */
  com.google.protobuf.ByteString
      getRequireProducerBytes(int index);

  /**
   * <code>string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
