// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Protocol.proto

package com.chuhui.marshal.framework.transfer.google;

public interface ProducerRequestPackageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.chuhui.marshal.framework.transfer.google.ProducerRequestPackage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string serverGroup = 1;</code>
   */
  java.lang.String getServerGroup();
  /**
   * <code>string serverGroup = 1;</code>
   */
  com.google.protobuf.ByteString
      getServerGroupBytes();

  /**
   * <code>string selfAddress = 2;</code>
   */
  java.lang.String getSelfAddress();
  /**
   * <code>string selfAddress = 2;</code>
   */
  com.google.protobuf.ByteString
      getSelfAddressBytes();

  /**
   * <code>string serverName = 3;</code>
   */
  java.lang.String getServerName();
  /**
   * <code>string serverName = 3;</code>
   */
  com.google.protobuf.ByteString
      getServerNameBytes();

  /**
   * <code>repeated .com.chuhui.marshal.framework.transfer.google.ServiceDefinitionPackage definitions = 4;</code>
   */
  java.util.List<com.chuhui.marshal.framework.transfer.google.ServiceDefinitionPackage> 
      getDefinitionsList();
  /**
   * <code>repeated .com.chuhui.marshal.framework.transfer.google.ServiceDefinitionPackage definitions = 4;</code>
   */
  com.chuhui.marshal.framework.transfer.google.ServiceDefinitionPackage getDefinitions(int index);
  /**
   * <code>repeated .com.chuhui.marshal.framework.transfer.google.ServiceDefinitionPackage definitions = 4;</code>
   */
  int getDefinitionsCount();
  /**
   * <code>repeated .com.chuhui.marshal.framework.transfer.google.ServiceDefinitionPackage definitions = 4;</code>
   */
  java.util.List<? extends com.chuhui.marshal.framework.transfer.google.ServiceDefinitionPackageOrBuilder> 
      getDefinitionsOrBuilderList();
  /**
   * <code>repeated .com.chuhui.marshal.framework.transfer.google.ServiceDefinitionPackage definitions = 4;</code>
   */
  com.chuhui.marshal.framework.transfer.google.ServiceDefinitionPackageOrBuilder getDefinitionsOrBuilder(
      int index);
}
