// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Protocol.proto

package com.chuhui.marshal.framework.transfer.google;

/**
 * Protobuf type {@code com.chuhui.marshal.framework.transfer.google.ProducerRequestPackage}
 */
public  final class ProducerRequestPackage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.chuhui.marshal.framework.transfer.google.ProducerRequestPackage)
    ProducerRequestPackageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ProducerRequestPackage.newBuilder() to construct.
  private ProducerRequestPackage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ProducerRequestPackage() {
    serverGroup_ = "";
    selfAddress_ = "";
    serverName_ = "";
    definitions_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ProducerRequestPackage(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            serverGroup_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            selfAddress_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            serverName_ = s;
            break;
          }
          case 34: {
            if (!((mutable_bitField0_ & 0x00000008) != 0)) {
              definitions_ = new java.util.ArrayList<com.chuhui.marshal.framework.transfer.google.ServiceDefinitionPackage>();
              mutable_bitField0_ |= 0x00000008;
            }
            definitions_.add(
                input.readMessage(com.chuhui.marshal.framework.transfer.google.ServiceDefinitionPackage.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000008) != 0)) {
        definitions_ = java.util.Collections.unmodifiableList(definitions_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.chuhui.marshal.framework.transfer.google.Protocol.internal_static_com_chuhui_marshal_framework_transfer_google_ProducerRequestPackage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.chuhui.marshal.framework.transfer.google.Protocol.internal_static_com_chuhui_marshal_framework_transfer_google_ProducerRequestPackage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.chuhui.marshal.framework.transfer.google.ProducerRequestPackage.class, com.chuhui.marshal.framework.transfer.google.ProducerRequestPackage.Builder.class);
  }

  private int bitField0_;
  public static final int SERVERGROUP_FIELD_NUMBER = 1;
  private volatile java.lang.Object serverGroup_;
  /**
   * <code>string serverGroup = 1;</code>
   */
  public java.lang.String getServerGroup() {
    java.lang.Object ref = serverGroup_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      serverGroup_ = s;
      return s;
    }
  }
  /**
   * <code>string serverGroup = 1;</code>
   */
  public com.google.protobuf.ByteString
      getServerGroupBytes() {
    java.lang.Object ref = serverGroup_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      serverGroup_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SELFADDRESS_FIELD_NUMBER = 2;
  private volatile java.lang.Object selfAddress_;
  /**
   * <code>string selfAddress = 2;</code>
   */
  public java.lang.String getSelfAddress() {
    java.lang.Object ref = selfAddress_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      selfAddress_ = s;
      return s;
    }
  }
  /**
   * <code>string selfAddress = 2;</code>
   */
  public com.google.protobuf.ByteString
      getSelfAddressBytes() {
    java.lang.Object ref = selfAddress_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      selfAddress_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SERVERNAME_FIELD_NUMBER = 3;
  private volatile java.lang.Object serverName_;
  /**
   * <code>string serverName = 3;</code>
   */
  public java.lang.String getServerName() {
    java.lang.Object ref = serverName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      serverName_ = s;
      return s;
    }
  }
  /**
   * <code>string serverName = 3;</code>
   */
  public com.google.protobuf.ByteString
      getServerNameBytes() {
    java.lang.Object ref = serverName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      serverName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DEFINITIONS_FIELD_NUMBER = 4;
  private java.util.List<com.chuhui.marshal.framework.transfer.google.ServiceDefinitionPackage> definitions_;
  /**
   * <code>repeated .com.chuhui.marshal.framework.transfer.google.ServiceDefinitionPackage definitions = 4;</code>
   */
  public java.util.List<com.chuhui.marshal.framework.transfer.google.ServiceDefinitionPackage> getDefinitionsList() {
    return definitions_;
  }
  /**
   * <code>repeated .com.chuhui.marshal.framework.transfer.google.ServiceDefinitionPackage definitions = 4;</code>
   */
  public java.util.List<? extends com.chuhui.marshal.framework.transfer.google.ServiceDefinitionPackageOrBuilder> 
      getDefinitionsOrBuilderList() {
    return definitions_;
  }
  /**
   * <code>repeated .com.chuhui.marshal.framework.transfer.google.ServiceDefinitionPackage definitions = 4;</code>
   */
  public int getDefinitionsCount() {
    return definitions_.size();
  }
  /**
   * <code>repeated .com.chuhui.marshal.framework.transfer.google.ServiceDefinitionPackage definitions = 4;</code>
   */
  public com.chuhui.marshal.framework.transfer.google.ServiceDefinitionPackage getDefinitions(int index) {
    return definitions_.get(index);
  }
  /**
   * <code>repeated .com.chuhui.marshal.framework.transfer.google.ServiceDefinitionPackage definitions = 4;</code>
   */
  public com.chuhui.marshal.framework.transfer.google.ServiceDefinitionPackageOrBuilder getDefinitionsOrBuilder(
      int index) {
    return definitions_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getServerGroupBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, serverGroup_);
    }
    if (!getSelfAddressBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, selfAddress_);
    }
    if (!getServerNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, serverName_);
    }
    for (int i = 0; i < definitions_.size(); i++) {
      output.writeMessage(4, definitions_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getServerGroupBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, serverGroup_);
    }
    if (!getSelfAddressBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, selfAddress_);
    }
    if (!getServerNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, serverName_);
    }
    for (int i = 0; i < definitions_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, definitions_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.chuhui.marshal.framework.transfer.google.ProducerRequestPackage)) {
      return super.equals(obj);
    }
    com.chuhui.marshal.framework.transfer.google.ProducerRequestPackage other = (com.chuhui.marshal.framework.transfer.google.ProducerRequestPackage) obj;

    if (!getServerGroup()
        .equals(other.getServerGroup())) return false;
    if (!getSelfAddress()
        .equals(other.getSelfAddress())) return false;
    if (!getServerName()
        .equals(other.getServerName())) return false;
    if (!getDefinitionsList()
        .equals(other.getDefinitionsList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SERVERGROUP_FIELD_NUMBER;
    hash = (53 * hash) + getServerGroup().hashCode();
    hash = (37 * hash) + SELFADDRESS_FIELD_NUMBER;
    hash = (53 * hash) + getSelfAddress().hashCode();
    hash = (37 * hash) + SERVERNAME_FIELD_NUMBER;
    hash = (53 * hash) + getServerName().hashCode();
    if (getDefinitionsCount() > 0) {
      hash = (37 * hash) + DEFINITIONS_FIELD_NUMBER;
      hash = (53 * hash) + getDefinitionsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.chuhui.marshal.framework.transfer.google.ProducerRequestPackage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.chuhui.marshal.framework.transfer.google.ProducerRequestPackage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.chuhui.marshal.framework.transfer.google.ProducerRequestPackage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.chuhui.marshal.framework.transfer.google.ProducerRequestPackage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.chuhui.marshal.framework.transfer.google.ProducerRequestPackage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.chuhui.marshal.framework.transfer.google.ProducerRequestPackage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.chuhui.marshal.framework.transfer.google.ProducerRequestPackage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.chuhui.marshal.framework.transfer.google.ProducerRequestPackage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.chuhui.marshal.framework.transfer.google.ProducerRequestPackage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.chuhui.marshal.framework.transfer.google.ProducerRequestPackage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.chuhui.marshal.framework.transfer.google.ProducerRequestPackage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.chuhui.marshal.framework.transfer.google.ProducerRequestPackage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.chuhui.marshal.framework.transfer.google.ProducerRequestPackage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.chuhui.marshal.framework.transfer.google.ProducerRequestPackage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.chuhui.marshal.framework.transfer.google.ProducerRequestPackage)
      com.chuhui.marshal.framework.transfer.google.ProducerRequestPackageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.chuhui.marshal.framework.transfer.google.Protocol.internal_static_com_chuhui_marshal_framework_transfer_google_ProducerRequestPackage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.chuhui.marshal.framework.transfer.google.Protocol.internal_static_com_chuhui_marshal_framework_transfer_google_ProducerRequestPackage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.chuhui.marshal.framework.transfer.google.ProducerRequestPackage.class, com.chuhui.marshal.framework.transfer.google.ProducerRequestPackage.Builder.class);
    }

    // Construct using com.chuhui.marshal.framework.transfer.google.ProducerRequestPackage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getDefinitionsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      serverGroup_ = "";

      selfAddress_ = "";

      serverName_ = "";

      if (definitionsBuilder_ == null) {
        definitions_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
      } else {
        definitionsBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.chuhui.marshal.framework.transfer.google.Protocol.internal_static_com_chuhui_marshal_framework_transfer_google_ProducerRequestPackage_descriptor;
    }

    @java.lang.Override
    public com.chuhui.marshal.framework.transfer.google.ProducerRequestPackage getDefaultInstanceForType() {
      return com.chuhui.marshal.framework.transfer.google.ProducerRequestPackage.getDefaultInstance();
    }

    @java.lang.Override
    public com.chuhui.marshal.framework.transfer.google.ProducerRequestPackage build() {
      com.chuhui.marshal.framework.transfer.google.ProducerRequestPackage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.chuhui.marshal.framework.transfer.google.ProducerRequestPackage buildPartial() {
      com.chuhui.marshal.framework.transfer.google.ProducerRequestPackage result = new com.chuhui.marshal.framework.transfer.google.ProducerRequestPackage(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.serverGroup_ = serverGroup_;
      result.selfAddress_ = selfAddress_;
      result.serverName_ = serverName_;
      if (definitionsBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0)) {
          definitions_ = java.util.Collections.unmodifiableList(definitions_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.definitions_ = definitions_;
      } else {
        result.definitions_ = definitionsBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.chuhui.marshal.framework.transfer.google.ProducerRequestPackage) {
        return mergeFrom((com.chuhui.marshal.framework.transfer.google.ProducerRequestPackage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.chuhui.marshal.framework.transfer.google.ProducerRequestPackage other) {
      if (other == com.chuhui.marshal.framework.transfer.google.ProducerRequestPackage.getDefaultInstance()) return this;
      if (!other.getServerGroup().isEmpty()) {
        serverGroup_ = other.serverGroup_;
        onChanged();
      }
      if (!other.getSelfAddress().isEmpty()) {
        selfAddress_ = other.selfAddress_;
        onChanged();
      }
      if (!other.getServerName().isEmpty()) {
        serverName_ = other.serverName_;
        onChanged();
      }
      if (definitionsBuilder_ == null) {
        if (!other.definitions_.isEmpty()) {
          if (definitions_.isEmpty()) {
            definitions_ = other.definitions_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureDefinitionsIsMutable();
            definitions_.addAll(other.definitions_);
          }
          onChanged();
        }
      } else {
        if (!other.definitions_.isEmpty()) {
          if (definitionsBuilder_.isEmpty()) {
            definitionsBuilder_.dispose();
            definitionsBuilder_ = null;
            definitions_ = other.definitions_;
            bitField0_ = (bitField0_ & ~0x00000008);
            definitionsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getDefinitionsFieldBuilder() : null;
          } else {
            definitionsBuilder_.addAllMessages(other.definitions_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.chuhui.marshal.framework.transfer.google.ProducerRequestPackage parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.chuhui.marshal.framework.transfer.google.ProducerRequestPackage) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object serverGroup_ = "";
    /**
     * <code>string serverGroup = 1;</code>
     */
    public java.lang.String getServerGroup() {
      java.lang.Object ref = serverGroup_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        serverGroup_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string serverGroup = 1;</code>
     */
    public com.google.protobuf.ByteString
        getServerGroupBytes() {
      java.lang.Object ref = serverGroup_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        serverGroup_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string serverGroup = 1;</code>
     */
    public Builder setServerGroup(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      serverGroup_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string serverGroup = 1;</code>
     */
    public Builder clearServerGroup() {
      
      serverGroup_ = getDefaultInstance().getServerGroup();
      onChanged();
      return this;
    }
    /**
     * <code>string serverGroup = 1;</code>
     */
    public Builder setServerGroupBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      serverGroup_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object selfAddress_ = "";
    /**
     * <code>string selfAddress = 2;</code>
     */
    public java.lang.String getSelfAddress() {
      java.lang.Object ref = selfAddress_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        selfAddress_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string selfAddress = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSelfAddressBytes() {
      java.lang.Object ref = selfAddress_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        selfAddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string selfAddress = 2;</code>
     */
    public Builder setSelfAddress(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      selfAddress_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string selfAddress = 2;</code>
     */
    public Builder clearSelfAddress() {
      
      selfAddress_ = getDefaultInstance().getSelfAddress();
      onChanged();
      return this;
    }
    /**
     * <code>string selfAddress = 2;</code>
     */
    public Builder setSelfAddressBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      selfAddress_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object serverName_ = "";
    /**
     * <code>string serverName = 3;</code>
     */
    public java.lang.String getServerName() {
      java.lang.Object ref = serverName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        serverName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string serverName = 3;</code>
     */
    public com.google.protobuf.ByteString
        getServerNameBytes() {
      java.lang.Object ref = serverName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        serverName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string serverName = 3;</code>
     */
    public Builder setServerName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      serverName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string serverName = 3;</code>
     */
    public Builder clearServerName() {
      
      serverName_ = getDefaultInstance().getServerName();
      onChanged();
      return this;
    }
    /**
     * <code>string serverName = 3;</code>
     */
    public Builder setServerNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      serverName_ = value;
      onChanged();
      return this;
    }

    private java.util.List<com.chuhui.marshal.framework.transfer.google.ServiceDefinitionPackage> definitions_ =
      java.util.Collections.emptyList();
    private void ensureDefinitionsIsMutable() {
      if (!((bitField0_ & 0x00000008) != 0)) {
        definitions_ = new java.util.ArrayList<com.chuhui.marshal.framework.transfer.google.ServiceDefinitionPackage>(definitions_);
        bitField0_ |= 0x00000008;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.chuhui.marshal.framework.transfer.google.ServiceDefinitionPackage, com.chuhui.marshal.framework.transfer.google.ServiceDefinitionPackage.Builder, com.chuhui.marshal.framework.transfer.google.ServiceDefinitionPackageOrBuilder> definitionsBuilder_;

    /**
     * <code>repeated .com.chuhui.marshal.framework.transfer.google.ServiceDefinitionPackage definitions = 4;</code>
     */
    public java.util.List<com.chuhui.marshal.framework.transfer.google.ServiceDefinitionPackage> getDefinitionsList() {
      if (definitionsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(definitions_);
      } else {
        return definitionsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.chuhui.marshal.framework.transfer.google.ServiceDefinitionPackage definitions = 4;</code>
     */
    public int getDefinitionsCount() {
      if (definitionsBuilder_ == null) {
        return definitions_.size();
      } else {
        return definitionsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.chuhui.marshal.framework.transfer.google.ServiceDefinitionPackage definitions = 4;</code>
     */
    public com.chuhui.marshal.framework.transfer.google.ServiceDefinitionPackage getDefinitions(int index) {
      if (definitionsBuilder_ == null) {
        return definitions_.get(index);
      } else {
        return definitionsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.chuhui.marshal.framework.transfer.google.ServiceDefinitionPackage definitions = 4;</code>
     */
    public Builder setDefinitions(
        int index, com.chuhui.marshal.framework.transfer.google.ServiceDefinitionPackage value) {
      if (definitionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDefinitionsIsMutable();
        definitions_.set(index, value);
        onChanged();
      } else {
        definitionsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.chuhui.marshal.framework.transfer.google.ServiceDefinitionPackage definitions = 4;</code>
     */
    public Builder setDefinitions(
        int index, com.chuhui.marshal.framework.transfer.google.ServiceDefinitionPackage.Builder builderForValue) {
      if (definitionsBuilder_ == null) {
        ensureDefinitionsIsMutable();
        definitions_.set(index, builderForValue.build());
        onChanged();
      } else {
        definitionsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.chuhui.marshal.framework.transfer.google.ServiceDefinitionPackage definitions = 4;</code>
     */
    public Builder addDefinitions(com.chuhui.marshal.framework.transfer.google.ServiceDefinitionPackage value) {
      if (definitionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDefinitionsIsMutable();
        definitions_.add(value);
        onChanged();
      } else {
        definitionsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.chuhui.marshal.framework.transfer.google.ServiceDefinitionPackage definitions = 4;</code>
     */
    public Builder addDefinitions(
        int index, com.chuhui.marshal.framework.transfer.google.ServiceDefinitionPackage value) {
      if (definitionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDefinitionsIsMutable();
        definitions_.add(index, value);
        onChanged();
      } else {
        definitionsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.chuhui.marshal.framework.transfer.google.ServiceDefinitionPackage definitions = 4;</code>
     */
    public Builder addDefinitions(
        com.chuhui.marshal.framework.transfer.google.ServiceDefinitionPackage.Builder builderForValue) {
      if (definitionsBuilder_ == null) {
        ensureDefinitionsIsMutable();
        definitions_.add(builderForValue.build());
        onChanged();
      } else {
        definitionsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.chuhui.marshal.framework.transfer.google.ServiceDefinitionPackage definitions = 4;</code>
     */
    public Builder addDefinitions(
        int index, com.chuhui.marshal.framework.transfer.google.ServiceDefinitionPackage.Builder builderForValue) {
      if (definitionsBuilder_ == null) {
        ensureDefinitionsIsMutable();
        definitions_.add(index, builderForValue.build());
        onChanged();
      } else {
        definitionsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.chuhui.marshal.framework.transfer.google.ServiceDefinitionPackage definitions = 4;</code>
     */
    public Builder addAllDefinitions(
        java.lang.Iterable<? extends com.chuhui.marshal.framework.transfer.google.ServiceDefinitionPackage> values) {
      if (definitionsBuilder_ == null) {
        ensureDefinitionsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, definitions_);
        onChanged();
      } else {
        definitionsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.chuhui.marshal.framework.transfer.google.ServiceDefinitionPackage definitions = 4;</code>
     */
    public Builder clearDefinitions() {
      if (definitionsBuilder_ == null) {
        definitions_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
      } else {
        definitionsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.chuhui.marshal.framework.transfer.google.ServiceDefinitionPackage definitions = 4;</code>
     */
    public Builder removeDefinitions(int index) {
      if (definitionsBuilder_ == null) {
        ensureDefinitionsIsMutable();
        definitions_.remove(index);
        onChanged();
      } else {
        definitionsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.chuhui.marshal.framework.transfer.google.ServiceDefinitionPackage definitions = 4;</code>
     */
    public com.chuhui.marshal.framework.transfer.google.ServiceDefinitionPackage.Builder getDefinitionsBuilder(
        int index) {
      return getDefinitionsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.chuhui.marshal.framework.transfer.google.ServiceDefinitionPackage definitions = 4;</code>
     */
    public com.chuhui.marshal.framework.transfer.google.ServiceDefinitionPackageOrBuilder getDefinitionsOrBuilder(
        int index) {
      if (definitionsBuilder_ == null) {
        return definitions_.get(index);  } else {
        return definitionsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.chuhui.marshal.framework.transfer.google.ServiceDefinitionPackage definitions = 4;</code>
     */
    public java.util.List<? extends com.chuhui.marshal.framework.transfer.google.ServiceDefinitionPackageOrBuilder> 
         getDefinitionsOrBuilderList() {
      if (definitionsBuilder_ != null) {
        return definitionsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(definitions_);
      }
    }
    /**
     * <code>repeated .com.chuhui.marshal.framework.transfer.google.ServiceDefinitionPackage definitions = 4;</code>
     */
    public com.chuhui.marshal.framework.transfer.google.ServiceDefinitionPackage.Builder addDefinitionsBuilder() {
      return getDefinitionsFieldBuilder().addBuilder(
          com.chuhui.marshal.framework.transfer.google.ServiceDefinitionPackage.getDefaultInstance());
    }
    /**
     * <code>repeated .com.chuhui.marshal.framework.transfer.google.ServiceDefinitionPackage definitions = 4;</code>
     */
    public com.chuhui.marshal.framework.transfer.google.ServiceDefinitionPackage.Builder addDefinitionsBuilder(
        int index) {
      return getDefinitionsFieldBuilder().addBuilder(
          index, com.chuhui.marshal.framework.transfer.google.ServiceDefinitionPackage.getDefaultInstance());
    }
    /**
     * <code>repeated .com.chuhui.marshal.framework.transfer.google.ServiceDefinitionPackage definitions = 4;</code>
     */
    public java.util.List<com.chuhui.marshal.framework.transfer.google.ServiceDefinitionPackage.Builder> 
         getDefinitionsBuilderList() {
      return getDefinitionsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.chuhui.marshal.framework.transfer.google.ServiceDefinitionPackage, com.chuhui.marshal.framework.transfer.google.ServiceDefinitionPackage.Builder, com.chuhui.marshal.framework.transfer.google.ServiceDefinitionPackageOrBuilder> 
        getDefinitionsFieldBuilder() {
      if (definitionsBuilder_ == null) {
        definitionsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.chuhui.marshal.framework.transfer.google.ServiceDefinitionPackage, com.chuhui.marshal.framework.transfer.google.ServiceDefinitionPackage.Builder, com.chuhui.marshal.framework.transfer.google.ServiceDefinitionPackageOrBuilder>(
                definitions_,
                ((bitField0_ & 0x00000008) != 0),
                getParentForChildren(),
                isClean());
        definitions_ = null;
      }
      return definitionsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.chuhui.marshal.framework.transfer.google.ProducerRequestPackage)
  }

  // @@protoc_insertion_point(class_scope:com.chuhui.marshal.framework.transfer.google.ProducerRequestPackage)
  private static final com.chuhui.marshal.framework.transfer.google.ProducerRequestPackage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.chuhui.marshal.framework.transfer.google.ProducerRequestPackage();
  }

  public static com.chuhui.marshal.framework.transfer.google.ProducerRequestPackage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ProducerRequestPackage>
      PARSER = new com.google.protobuf.AbstractParser<ProducerRequestPackage>() {
    @java.lang.Override
    public ProducerRequestPackage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ProducerRequestPackage(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ProducerRequestPackage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ProducerRequestPackage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.chuhui.marshal.framework.transfer.google.ProducerRequestPackage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

