// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Protocol.proto

package com.chuhui.marshal.framework.transfer.google;

public interface SearchServiceRequestPackageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.chuhui.marshal.framework.transfer.google.SearchServiceRequestPackage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string group = 1;</code>
   */
  java.lang.String getGroup();
  /**
   * <code>string group = 1;</code>
   */
  com.google.protobuf.ByteString
      getGroupBytes();

  /**
   * <code>string serviceUrl = 2;</code>
   */
  java.lang.String getServiceUrl();
  /**
   * <code>string serviceUrl = 2;</code>
   */
  com.google.protobuf.ByteString
      getServiceUrlBytes();
}
