// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Protocol.proto

package com.chuhui.marshal.framework.transfer;

/**
 * Protobuf type {@code com.chuhui.marshal.framework.transfer.ClientRequestPackage}
 */
public  final class ClientRequestPackage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.chuhui.marshal.framework.transfer.ClientRequestPackage)
    ClientRequestPackageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ClientRequestPackage.newBuilder() to construct.
  private ClientRequestPackage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ClientRequestPackage() {
    requireProducer_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    name_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ClientRequestPackage(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              requireProducer_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            requireProducer_.add(s);
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 24: {

            requestFlag_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        requireProducer_ = requireProducer_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.chuhui.marshal.framework.transfer.Protocol.internal_static_com_chuhui_marshal_framework_transfer_ClientRequestPackage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.chuhui.marshal.framework.transfer.Protocol.internal_static_com_chuhui_marshal_framework_transfer_ClientRequestPackage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.chuhui.marshal.framework.transfer.ClientRequestPackage.class, com.chuhui.marshal.framework.transfer.ClientRequestPackage.Builder.class);
  }

  private int bitField0_;
  public static final int REQUIREPRODUCER_FIELD_NUMBER = 1;
  private com.google.protobuf.LazyStringList requireProducer_;
  /**
   * <code>repeated string requireProducer = 1;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getRequireProducerList() {
    return requireProducer_;
  }
  /**
   * <code>repeated string requireProducer = 1;</code>
   */
  public int getRequireProducerCount() {
    return requireProducer_.size();
  }
  /**
   * <code>repeated string requireProducer = 1;</code>
   */
  public java.lang.String getRequireProducer(int index) {
    return requireProducer_.get(index);
  }
  /**
   * <code>repeated string requireProducer = 1;</code>
   */
  public com.google.protobuf.ByteString
      getRequireProducerBytes(int index) {
    return requireProducer_.getByteString(index);
  }

  public static final int NAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object name_;
  /**
   * <code>string name = 2;</code>
   */
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 2;</code>
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int REQUESTFLAG_FIELD_NUMBER = 3;
  private int requestFlag_;
  /**
   * <code>int32 requestFlag = 3;</code>
   */
  public int getRequestFlag() {
    return requestFlag_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < requireProducer_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, requireProducer_.getRaw(i));
    }
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
    }
    if (requestFlag_ != 0) {
      output.writeInt32(3, requestFlag_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < requireProducer_.size(); i++) {
        dataSize += computeStringSizeNoTag(requireProducer_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getRequireProducerList().size();
    }
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
    }
    if (requestFlag_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, requestFlag_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.chuhui.marshal.framework.transfer.ClientRequestPackage)) {
      return super.equals(obj);
    }
    com.chuhui.marshal.framework.transfer.ClientRequestPackage other = (com.chuhui.marshal.framework.transfer.ClientRequestPackage) obj;

    if (!getRequireProducerList()
        .equals(other.getRequireProducerList())) return false;
    if (!getName()
        .equals(other.getName())) return false;
    if (getRequestFlag()
        != other.getRequestFlag()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getRequireProducerCount() > 0) {
      hash = (37 * hash) + REQUIREPRODUCER_FIELD_NUMBER;
      hash = (53 * hash) + getRequireProducerList().hashCode();
    }
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + REQUESTFLAG_FIELD_NUMBER;
    hash = (53 * hash) + getRequestFlag();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.chuhui.marshal.framework.transfer.ClientRequestPackage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.chuhui.marshal.framework.transfer.ClientRequestPackage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.chuhui.marshal.framework.transfer.ClientRequestPackage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.chuhui.marshal.framework.transfer.ClientRequestPackage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.chuhui.marshal.framework.transfer.ClientRequestPackage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.chuhui.marshal.framework.transfer.ClientRequestPackage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.chuhui.marshal.framework.transfer.ClientRequestPackage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.chuhui.marshal.framework.transfer.ClientRequestPackage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.chuhui.marshal.framework.transfer.ClientRequestPackage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.chuhui.marshal.framework.transfer.ClientRequestPackage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.chuhui.marshal.framework.transfer.ClientRequestPackage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.chuhui.marshal.framework.transfer.ClientRequestPackage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.chuhui.marshal.framework.transfer.ClientRequestPackage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.chuhui.marshal.framework.transfer.ClientRequestPackage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.chuhui.marshal.framework.transfer.ClientRequestPackage)
      com.chuhui.marshal.framework.transfer.ClientRequestPackageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.chuhui.marshal.framework.transfer.Protocol.internal_static_com_chuhui_marshal_framework_transfer_ClientRequestPackage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.chuhui.marshal.framework.transfer.Protocol.internal_static_com_chuhui_marshal_framework_transfer_ClientRequestPackage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.chuhui.marshal.framework.transfer.ClientRequestPackage.class, com.chuhui.marshal.framework.transfer.ClientRequestPackage.Builder.class);
    }

    // Construct using com.chuhui.marshal.framework.transfer.ClientRequestPackage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      requireProducer_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      name_ = "";

      requestFlag_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.chuhui.marshal.framework.transfer.Protocol.internal_static_com_chuhui_marshal_framework_transfer_ClientRequestPackage_descriptor;
    }

    @java.lang.Override
    public com.chuhui.marshal.framework.transfer.ClientRequestPackage getDefaultInstanceForType() {
      return com.chuhui.marshal.framework.transfer.ClientRequestPackage.getDefaultInstance();
    }

    @java.lang.Override
    public com.chuhui.marshal.framework.transfer.ClientRequestPackage build() {
      com.chuhui.marshal.framework.transfer.ClientRequestPackage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.chuhui.marshal.framework.transfer.ClientRequestPackage buildPartial() {
      com.chuhui.marshal.framework.transfer.ClientRequestPackage result = new com.chuhui.marshal.framework.transfer.ClientRequestPackage(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        requireProducer_ = requireProducer_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.requireProducer_ = requireProducer_;
      result.name_ = name_;
      result.requestFlag_ = requestFlag_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.chuhui.marshal.framework.transfer.ClientRequestPackage) {
        return mergeFrom((com.chuhui.marshal.framework.transfer.ClientRequestPackage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.chuhui.marshal.framework.transfer.ClientRequestPackage other) {
      if (other == com.chuhui.marshal.framework.transfer.ClientRequestPackage.getDefaultInstance()) return this;
      if (!other.requireProducer_.isEmpty()) {
        if (requireProducer_.isEmpty()) {
          requireProducer_ = other.requireProducer_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureRequireProducerIsMutable();
          requireProducer_.addAll(other.requireProducer_);
        }
        onChanged();
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (other.getRequestFlag() != 0) {
        setRequestFlag(other.getRequestFlag());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.chuhui.marshal.framework.transfer.ClientRequestPackage parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.chuhui.marshal.framework.transfer.ClientRequestPackage) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.LazyStringList requireProducer_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureRequireProducerIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        requireProducer_ = new com.google.protobuf.LazyStringArrayList(requireProducer_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated string requireProducer = 1;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getRequireProducerList() {
      return requireProducer_.getUnmodifiableView();
    }
    /**
     * <code>repeated string requireProducer = 1;</code>
     */
    public int getRequireProducerCount() {
      return requireProducer_.size();
    }
    /**
     * <code>repeated string requireProducer = 1;</code>
     */
    public java.lang.String getRequireProducer(int index) {
      return requireProducer_.get(index);
    }
    /**
     * <code>repeated string requireProducer = 1;</code>
     */
    public com.google.protobuf.ByteString
        getRequireProducerBytes(int index) {
      return requireProducer_.getByteString(index);
    }
    /**
     * <code>repeated string requireProducer = 1;</code>
     */
    public Builder setRequireProducer(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureRequireProducerIsMutable();
      requireProducer_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string requireProducer = 1;</code>
     */
    public Builder addRequireProducer(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureRequireProducerIsMutable();
      requireProducer_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string requireProducer = 1;</code>
     */
    public Builder addAllRequireProducer(
        java.lang.Iterable<java.lang.String> values) {
      ensureRequireProducerIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, requireProducer_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string requireProducer = 1;</code>
     */
    public Builder clearRequireProducer() {
      requireProducer_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string requireProducer = 1;</code>
     */
    public Builder addRequireProducerBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureRequireProducerIsMutable();
      requireProducer_.add(value);
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 2;</code>
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private int requestFlag_ ;
    /**
     * <code>int32 requestFlag = 3;</code>
     */
    public int getRequestFlag() {
      return requestFlag_;
    }
    /**
     * <code>int32 requestFlag = 3;</code>
     */
    public Builder setRequestFlag(int value) {
      
      requestFlag_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 requestFlag = 3;</code>
     */
    public Builder clearRequestFlag() {
      
      requestFlag_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.chuhui.marshal.framework.transfer.ClientRequestPackage)
  }

  // @@protoc_insertion_point(class_scope:com.chuhui.marshal.framework.transfer.ClientRequestPackage)
  private static final com.chuhui.marshal.framework.transfer.ClientRequestPackage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.chuhui.marshal.framework.transfer.ClientRequestPackage();
  }

  public static com.chuhui.marshal.framework.transfer.ClientRequestPackage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ClientRequestPackage>
      PARSER = new com.google.protobuf.AbstractParser<ClientRequestPackage>() {
    @java.lang.Override
    public ClientRequestPackage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ClientRequestPackage(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ClientRequestPackage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ClientRequestPackage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.chuhui.marshal.framework.transfer.ClientRequestPackage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

