// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Protocol.proto

package com.chuhui.marshal.framework.transfer;

public interface ClientRequestPackageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.chuhui.marshal.framework.transfer.ClientRequestPackage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string requireProducer = 1;</code>
   */
  java.util.List<String>
      getRequireProducerList();
  /**
   * <code>repeated string requireProducer = 1;</code>
   */
  int getRequireProducerCount();
  /**
   * <code>repeated string requireProducer = 1;</code>
   */
  String getRequireProducer(int index);
  /**
   * <code>repeated string requireProducer = 1;</code>
   */
  com.google.protobuf.ByteString
      getRequireProducerBytes(int index);

  /**
   * <code>string name = 2;</code>
   */
  String getName();
  /**
   * <code>string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 requestFlag = 3;</code>
   */
  int getRequestFlag();
}
