// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Protocol.proto

package com.chuhui.marshal.framework.transfer;

public final class Protocol {
  private Protocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_chuhui_marshal_framework_transfer_ClientRequestPackage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_chuhui_marshal_framework_transfer_ClientRequestPackage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\016Protocol.proto\022%com.chuhui.marshal.fra" +
      "mework.transfer\"R\n\024ClientRequestPackage\022" +
      "\027\n\017requireProducer\030\001 \003(\t\022\014\n\004name\030\002 \001(\t\022\023" +
      "\n\013requestFlag\030\003 \001(\005B)\n%com.chuhui.marsha" +
      "l.framework.transferP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_chuhui_marshal_framework_transfer_ClientRequestPackage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_chuhui_marshal_framework_transfer_ClientRequestPackage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_chuhui_marshal_framework_transfer_ClientRequestPackage_descriptor,
        new String[] { "RequireProducer", "Name", "RequestFlag", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
